name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pipeline: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: Remove problematic @types/babel__traverse
        run: rm -rf node_modules/@types/babel__traverse
      - name: build production project
        timeout-minutes: 2
        run: npm run build:prod
      - name: Check build status
        run: echo "Exit code: $?
      - name: List files after build
        run: ls -la
      - name: linting typescript
        run: npm run lint:ts
      - name: linting css
        run: npm run lint:css
      - name: unit testing
        run: npm run test:unit
